version: "3.8"

services:
  redpanda:
    image: redpandadata/redpanda:v22.2.2
    container_name: redpanda_kafka_queue
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --kafka-addr PLAINTEXT://0.0.0.0:29092
      - --advertise-kafka-addr PLAINTEXT://localhost:29092
    ports:
      - "29092:29092"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  redpanda_data:
