apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_TTL: "999999999999999999999999999999999999"
  KAFKA_BROKER: "redpanda.default.svc.cluster.local:9092"
  FRONTEND_ORIGIN: "http://frontend"
