apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: chat-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: xfarkasp/chat-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5004
          envFrom:
            - configMapRef:
                name: chat-service-config
            - secretRef:
                name: chat-service-secret
          livenessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP
