apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-config
data:
  PORT: "5004"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "chatapp"
  DB_NAME: "chatdb"
  KAFKA_BROKER: "redpanda.default.svc.cluster.local:9092"
  FRONTEND_ORIGIN: "http://frontend"
