apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  PORT: "5002"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "chatapp"
  DB_NAME: "userdb"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BROKER: "redpanda.chat-services.svc.cluster.local:9092"
  FRONTEND_ORIGIN: "http://frontend"
