apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: chat-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-service
  template:
    metadata:
      labels:
        app: websocket-service
    spec:
      containers:
        - name: websocket-service
          image: xfarkasp/websocket-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5003
          envFrom:
            - configMapRef:
                name: websocket-service-config
          env:
            - name: INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  selector:
    app: websocket-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP
